[programs.localnet]
voto_electronico = "BUsPJxSLyeiGjLNgwT2NrJVGqVhEWtErqWTDhfSravnv"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/cooper73/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
